#!/bin/bash
# shellcheck shell=bash

if [[ ! $# -gt 0 ]]; then
  echo "You need to specify which users to show"
  exit 0
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for i in "$@"; do
  if [[ "${i}" =~ ^[0-9]+$ ]]; then
    USER_ID="user${i}"
  else
    USER_ID="user_${i//[^[:alnum:]_-]/}"
  fi

  if [[ -d "${ROOT_DIR}/configs/shadowsocks2022/${USER_ID}" ]]; then
    echo "Shadowsocks USER ${i} QR code:"
    qrencode -t ansiutf8 < ${ROOT_DIR}/configs/shadowsocks2022/${USER_ID}/${USER_ID}.txt
  else
    echo "USER ${i} is not active"
  fi
done
