[Interface]
Address = 10.100.0.2/32 # INTERNAL_SERVER_SUBNET/32 - но host ID уникальный! (<- .2)
PrivateKey = <SERVER_PRIVATE_KEY>
MTU = 1380
# Таблица маршрутизации - не изменяет default route! задаем маршрут при запуске композа
Table = off

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
PresharedKey = <SERVER_PRESHARED_KEY>
Endpoint = VPS_IP:51820
AllowedIPs = 0.0.0.0/0, 128.0.0.0/1
PersistentKeepalive = 25
