[Interface]
Address = 10.100.0.2/32 # INTERNAL_SERVER_SUBNET/32 - но host ID уникальный! (<- .2)
PrivateKey = <CLIENT_PRIVATE_KEY>
MTU = 1380

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = VPS_IP:51820
AllowedIPs = 0.0.0.0/0 # Server Address/32
PersistentKeepalive = 25
